development:
  adapter: mysql2
  encoding: utf8
  database: hyperlocal_dev
  username:
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: hyperlocal_test
  username:
  password:
  socket: /tmp/mysql.sock
